config/routes.rb
Rails.application.routes.draw do
  resources :dts_hourlies
  devise_for :people
  resources :people
  resources :names
  resources :activity
  get "/dts", to: "dts_hourlies#dts", as: "dts"
  get "/dts/hourly/live", to: "dts_hourlies#dts_hourlies_live", as: "dts_hourlies_live"
  get "/dts/daypart", to: "dts_hourlies#daypart", as: "daypart"
  get "/dts/daypart/do", to: "dts_hourlies#daypart_do"
  get "/dts/hourly/live/do", to: "dts_hourlies#dts_hourlies_live_do"
  get "/dts/do", to: "dts_hourlies#dts_do", as: "dts_do"
  get "/app/views/home/index", to: "home#index", as: "index"
  get "/setup", to: "home#setup", as: "setup"
  get "/store", to: "home#store", as: "store"
  get "/setup/dp/do", to: "home#setup_dp_do", as: "setup_dp_do"
  get "/dts/fetch", to: "dts_hourlies#dts_fetch", as: "dts_fetch"
  root 'home#index'
end

app/models/name.rb
class Name
  include Mongoid::Document
  
  validates :firstname, presence: true,
                        length: { maximum: 50 }
  validates :lastname, presence: true,
                        length: { maximum: 50 }
  
  field :id, type: String
  field :firstname, type: String
  field :lastname, type: String
  field :store, type: String
  field :personId, type: String
  field :nameid, type: Integer
  field :active, type: Mongoid::Boolean
  
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  
  before_action :set_name, only: [:show, :edit, :update, :destroy]

  # GET /names
  # GET /names.json
  def index
    if current_person.admin
      @names = Name.all
    else
      @name = Name.find(@current_person.nameid)
    end
  end

  # GET /names/1
  # GET /names/1.json
  def show
    @name = Name.find(params[:id])
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
    @name = Name.find(params[:id])
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(name_params)
    
    respond_to do |format|
      if @name.save
        format.html { redirect_to names_url, notice: 'Name was successfully created.' }
        format.json { render :show, status: :created, location: @name }
      else
        format.html { render :new }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /names/1
  # PATCH/PUT /names/1.json
  def update
    respond_to do |format|
      if @name.update(name_params)
        format.html { redirect_to names_url, notice: 'Name was successfully updated.' }
        format.json { render :show, status: :ok, location: @name }
      else
        format.html { render :edit }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1
  # DELETE /names/1.json
  def destroy
    @name.destroy
    respond_to do |format|
      format.html { redirect_to names_url, notice: 'Name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def name_params
      params.require(:name).permit(:id, :firstname, :lastname, :store, :personId, :nameid, :active)
    end
end

app/views/names/_form.html.erb
<%= form_for @name, :html => { :class => "form-horizontal name" } do |f| %>

  <% if @name.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@name.errors.count, "error") %> prohibited this name from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @name.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :firstname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :firstname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:firstname) %>
  </div>
  <div class="form-group">
    <%= f.label :lastname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lastname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lastname) %>
  </div>
  
  <div class="form-group">
    <%= f.label :store, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :store, ["0335", "0610", "0771", "0858", "1098", "1330"], :prompt =>["Select One"], :class => 'form-control' %>
    </div>
    <%=f.error_span(:store) %>
  </div>
  <div class="form-group">
    <%= f.label :nameid, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nameid, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nameid) %>
  </div>
  
  <div class="form-group">
    <%= f.label :active, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :active, :class => 'inline-checkbox' %>
    </div>
    <%=f.error_span(:active) %>
  </div>
  

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                names_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/names/_formupdate.html.erb
<%= form_for @name, :html => { :class => "form-horizontal name" } do |f| %>

  <% if @name.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@name.errors.count, "error") %> prohibited this name from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @name.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :firstname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :firstname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:firstname) %>
  </div>
  <div class="form-group">
    <%= f.label :lastname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lastname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lastname) %>
  </div>
  
  
  <div class="form-group">
    <% if current_person.try(:admin?) %>
    <%= f.label :store, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :store,
      ["0335", "0610", "0771", "0858", "1098", "1330"],
      :prompt =>["Select One"],
      :class => 'form-control' %>
    </div>
    <%=f.error_span(:store) %>
  </div>
  <% else %>
    <div class="form-group">
    <%= f.label :store, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :store,
      :class => 'form-control',
      :readonly => !current_person.admin %>
    </div>
    <%=f.error_span(:store) %>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :personId, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :personId,
      :class => 'form-control',
      :readonly => !current_person.admin %>
    </div>
    <%=f.error_span(:personId) %>
  </div>
  <div class="form-group">
    <%= f.label :nameid, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nameid,
      :class => 'form-control',
      :readonly => !current_person.admin %>
    </div>
    <%=f.error_span(:nameid) %>
  </div>
  <div class="form-group">
    <%= f.label :active, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :active,
      :class => 'inline-checkbox',
      :disabled => !current_person.admin %>
    </div>
    <%=f.error_span(:active) %>
  </div>
  

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                names_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/names/edit.html.erb
<%- model_class = Name -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'formupdate' %>

app/views/names/edit.js.erb
$('#formfor').html("<%= j (render :partial => 'formupdate') %>");
$('#formfor').slideDown(350);

app/views/names/index.html.erb
<%- model_class = Name -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= flash_messages %>

<div id="formfor" style="width: 500px;">

</div>
<table class="table table-hover table-responsive" style="font-size: small;">
  <thead>
    <tr>
      <th>Name</th>
      <th><%= model_class.human_attribute_name(:store) %></th>
      <th><%= model_class.human_attribute_name(:personId) %></th>
      <th><%= model_class.human_attribute_name(:nameid) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% if defined?(@names) %>
    <% @names.each do |name| %>
      <tr>
        <td><%= link_to "#{name.firstname} #{name.lastname}", name_path(name) %></td>
        
        <td><%= name.store %></td>
        <td><%= name.personId %></td>
        <td><%= name.nameid %></td>
        <td><%= name.active %></td>
        
        
        <td>
          <div class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
          <ul class="dropdown-menu">
            
                <li><%= link_to t('.show', :default => t("helpers.links.show")),
                      name_path(name) %></li>
                <li><%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_name_path(name),
                        :remote => true %></li>
                <% if current_person.try(:admin?) %>
                <li role="separator" class="divider"></li>
                <li><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      name_path(name),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => "Are you sure you want to delete #{name.firstname} #{name.lastname}?")) },
                      :disable_with => "Loading...",
                      :class => 'bg-danger text-black' %>  
                </li>
                <% end %>
            </ul>
          </div>
          
          
          
        </td>
      </tr>
    <% end %>
    <% end %>
    <% if defined?(@name) %>
    <tr>
        <td><%= link_to "#{@name.firstname} #{@name.lastname}", name_path(@name) %></td>
        
        <td><%= @name.store %></td>
        <td><%= @name.personId %></td>
        <td><%= @name.nameid %></td>
        <td><%= @name.active %></td>
        
        
        <td>
          <div class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
          <ul class="dropdown-menu">
            
                <li><%= link_to t('.show', :default => t("helpers.links.show")),
                      name_path(@name) %></li>
                <li><%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_name_path(@name),
                        :remote => true %></li>
                <% if current_person.try(:admin?) %>
                <li role="separator" class="divider"></li>
                <li><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      name_path(@name),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => "Are you sure you want to delete #{@name.firstname} #{@name.lastname}?")) },
                      :disable_with => "Loading...",
                      :class => 'bg-danger text-black' %>  
                </li>
                <% end %>
            </ul>
          </div>
          
          
          
        </td>
      </tr>
      <% end %>
  </tbody>
</table>
<% if current_person.try(:admin?) %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_name_path,
            :remote => true,
            :class => 'btn btn-default' %>
<% end %></br>

app/views/names/new.html.erb
<%- model_class = Name -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/names/show.html.erb
<%- model_class = Name -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<%= flash_messages %>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:firstname) %>:</strong></dt>
  <dd><%= @name.firstname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lastname) %>:</strong></dt>
  <dd><%= @name.lastname %></dd>
  
  <dt><strong><%= model_class.human_attribute_name(:store) %>:</strong></dt>
  <dd><%= @name.store %></dd>
  <dt><strong><%= model_class.human_attribute_name(:personId) %>:</strong></dt>
  <dd><%= @name.personId %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nameid) %>:</strong></dt>
  <dd><%= @name.nameid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @name.active %></dd>
  
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              names_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_name_path(@name), :class => 'btn btn-default' %>
<% if current_person.try(:admin?) %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              name_path(@name),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>