config/routes.rb
Rails.application.routes.draw do
  resources :dts_hourlies
  devise_for :people
  resources :people
  resources :names
  resources :activity
  get "/dts", to: "dts_hourlies#dts", as: "dts"
  get "/dts/hourly/live", to: "dts_hourlies#dts_hourlies_live", as: "dts_hourlies_live"
  get "/dts/daypart", to: "dts_hourlies#daypart", as: "daypart"
  get "/dts/daypart/do", to: "dts_hourlies#daypart_do"
  get "/dts/hourly/live/do", to: "dts_hourlies#dts_hourlies_live_do"
  get "/dts/do", to: "dts_hourlies#dts_do", as: "dts_do"
  get "/app/views/home/index", to: "home#index", as: "index"
  get "/setup", to: "home#setup", as: "setup"
  get "/store", to: "home#store", as: "store"
  get "/setup/dp/do", to: "home#setup_dp_do", as: "setup_dp_do"
  get "/dts/fetch", to: "dts_hourlies#dts_fetch", as: "dts_fetch"
  root 'home#index'
end

app/models/dts_hourly.rb
class DtsHourly
  include Mongoid::Document
  field :date, :type => DateTime
  field :datestring, type: String
  field :hour, type: Integer
  field :cars, type: Integer
  field :COD1, type: Integer
  field :COD2, type: Integer
  field :HHOT, type: Integer
  field :Cashier, type: Integer
  field :Presenter, type: Integer
  field :OEPE, type: Integer
  field :AST, type: Integer
  field :TAR_COD1, type: Integer
  field :TAR_COD2, type: Integer
  field :TAR_HHOT, type: Integer
  field :TAR_Cashier, type: Integer
  field :TAR_Presenter, type: Integer
  field :TAR_OEPE, type: Integer
  field :TAR_AST, type: Integer
  field :storeId, type: String
end

app/controllers/dts_hourlies_controller.rb
class DtsHourliesController < ApplicationController
  before_action :set_dts_hourly, only: [:show, :edit, :update, :destroy]
  
  # GET /dts_hourlies
  # GET /dts_hourlies.json
  def index
    @storename = Hash[]
    if current_person.try(:admin?)
      @dts_hourlies = DtsHourly.all
      @stores = @dts_hourlies.uniq{|x| x.storeId}
      @stores.each do |store|   
        @storename[store.storeId] = reportinginit(store.storeId)
      end   
    else
      @all_hourlies = DtsHourly.all
      @dts_hourlies = Array[]
      @all_hourlies.each do |hourly|
        if hourly.storeId == current_person.store
          @dts_hourlies.push(hourly)
        end
      end
      @stores = @dts_hourlies.uniq{|x| x.storeId}
      @stores.each do |store|   
        @storename[store.storeId] = reportinginit(store.storeId)
      end
    end
  end

  # GET /dts_hourlies/1
  # GET /dts_hourlies/1.json
  def show
  end

  def daypart_do
    @daypart_arr = Array[]
    @daypart_str = Array[]
    @daypart_str[1] = "Overnight"
    @daypart_str[2] = "Open"
    @daypart_str[3] = "Dayshift"
    @daypart_str[4] = "Evening"
    if (params[:storeId] != "" && params[:storeId] != nil)
      @storeId = params[:storeId]
    else
      @storeId = "0000"
    end
    @storename = Hash[]
    @storename[@storeId] = reportinginit(@storeId)
    if (params[:date] != "" && params[:date] != nil)
      @date = params[:date]
    else
      @date = "1960-01-01"
    end
    if (params[:daypart] != "" && params[:daypart] != nil)
      @daypart_num = params[:daypart]
    end
    case @daypart_num.to_i
      when 1 #overnight
        @data = Dayparts.find_by(storeId: @storeId, daypart_num: 1)
        if @data == nil
          @daypart_arr[0] = 0
          @daypart_arr[1] = 5
        else
          @daypart_arr[0] = @data.start
          @daypart_arr[1] = @data.finish
        end
        
      when 2 #open
        @data = Dayparts.find_by(storeId: @storeId, daypart_num: 2)
        if @data == nil
          @daypart_arr[0] = 6
          @daypart_arr[1] = 6
        else
          @daypart_arr[0] = @data.start
          @daypart_arr[1] = @data.finish
        end
      when 3 #dayshift
        @data = Dayparts.find_by(storeId: @storeId, daypart_num: 3)
        if @data == nil
          @daypart_arr[0] = 7
          @daypart_arr[1] = 15
        else
          @daypart_arr[0] = @data.start
          @daypart_arr[1] = @data.finish
        end
      when 4 #evening
        @data = Dayparts.find_by(storeId: @storeId, daypart_num: 4)
        if @data == nil
          @daypart_arr[0] = 16
          @daypart_arr[1] = 23
        else
          @daypart_arr[0] = @data.start
          @daypart_arr[1] = @data.finish
        end
      else
        
        @daypart_arr[0] = 24
        @daypart_arr[1] = 24
    end
    array = Array[]
    @ast = 0
    @oepe = 0
    @avg_ast = 0
    @avg_oepe = 0
    @cars = 0
    log("Daypart read: (#{@storeId}) #{@date} #{@daypart_str[@daypart_num.to_i]}")
    DtsHourly.where(storeId: @storeId, datestring: @date, :hour.gte => @daypart_arr[0], :hour.lte => @daypart_arr[1]).all.each do |hour|
      array.push(hour)
      @ast += hour.AST
      @oepe += hour.OEPE
      @cars += hour.cars
    end  
    @return = array
    if ((@daypart_arr[1]-@daypart_arr[0]+1) != 0)
      @avg_ast = @ast / (@daypart_arr[1]-@daypart_arr[0]+1)
      @avg_oepe = @oepe / (@daypart_arr[1]-@daypart_arr[0]+1)
    else
      @avg_ast = 0
      @avg_oepe = 0
    end
  end

  def daypart
    
  end

  def url_hourly(businessUnitId)
    return URI("https://dtld-poc.appspot.com/_ah/api/dtldapi/v1/drivethrudashboard/hourlysummary?businessUnitId=#{businessUnitId}&withDbUpdate=2")
  end

  def url_reportdata(storeId, date, dayPart, reportType)
    if (dayPart == nil)
      dayPart = "Full"
    end
    if (reportType == nil)
      reportType = "Daily"
    end
    return URI("https://dtld-poc.appspot.com/_ah/api/dtldapi/v1/reporting/getreportdata?storeId=#{storeId}&businessDay=#{date}&dayPart=#{dayPart}&reportType=#{reportType}")

  end

  def dts_do
    if (params[:businessUnitId] != nil)
      @@businessUnitId = params[:businessUnitId]
      url_hourlysummary = url_hourly(@@businessUnitId)
      url_daily = URI("https://dtld-poc.appspot.com/_ah/api/dtldapi/v1/drivethrudashboard/dailyranking?businessUnitId=#{@@businessUnitId}")
      
      http = Net::HTTP.new(url_daily.host, url_daily.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE

      http2 = Net::HTTP.new(url_hourlysummary.host, url_hourlysummary.port)
      http2.use_ssl = true
      http2.verify_mode = OpenSSL::SSL::VERIFY_NONE

      response_daily = http.request(Net::HTTP::Get.new(url_daily))
      
      @hourlysummary = Array[]
      stores = Array[]
      storenames = Array[]
      if response_daily.read_body != nil
        daily = JSON.parse(response_daily.read_body)
        daily["items"].each_with_index do |item,index|
          if index>2
          stores.push(item["businessUnitId"])
          storenames.push(item["storeName"])
          end
        end
        for i in 0..stores.length-1
          url = url_hourly(stores[i])
          response_hourly = http2.request(Net::HTTP::Get.new(url))
          resp = JSON.parse(response_hourly.read_body)
          resp["store"] = storenames[i]
          resp["error"] = false
          @hourlysummary.push(resp)
        end
      else
        stringling = "Store #{@@businessUnitId} is not configured."
        respo = JSON.parse('{"error" : true }')
        respo["message"] = stringling
        @hourlysummary.push(respo)
      end
      @dailyranking = daily
    else
        if (current_person[:store] != nil)
    @@businessUnitId = current_person[:store]
      url_hourlysummary = url_hourly(@@businessUnitId)
      url_daily = URI("https://dtld-poc.appspot.com/_ah/api/dtldapi/v1/drivethrudashboard/dailyranking?businessUnitId=#{@@businessUnitId}")
      
      http = Net::HTTP.new(url_daily.host, url_daily.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE

      http2 = Net::HTTP.new(url_hourlysummary.host, url_hourlysummary.port)
      http2.use_ssl = true
      http2.verify_mode = OpenSSL::SSL::VERIFY_NONE

      response_daily = http.request(Net::HTTP::Get.new(url_daily))
      
      @hourlysummary = Array[]
      stores = Array[]
      storenames = Array[]
      if response_daily.read_body != nil
        daily = JSON.parse(response_daily.read_body)
        daily["items"].each_with_index do |item,index|
          if index>2
          stores.push(item["businessUnitId"])
          storenames.push(item["storeName"])
          end
        end
        for i in 0..stores.length-1
          url = url_hourly(stores[i])
          response_hourly = http2.request(Net::HTTP::Get.new(url))
          resp = JSON.parse(response_hourly.read_body)
          resp["store"] = storenames[i]
          resp["error"] = false
          @hourlysummary.push(resp)
        end
      else
        stringling = "Store #{@@businessUnitId} is not configured."
        respo = JSON.parse('{"error" : true }')
        respo["message"] = stringling
        @hourlysummary.push(respo)
      end
      @dailyranking = daily
    else
        @hourlysummary = Array[]
        stringling = "Store number not supplied."
        respo = JSON.parse('{"error" : true }')
        respo["message"] = stringling
        @hourlysummary.push(respo)
        @dailyranking = nil
    end
    end
  end

  def reportinginit(businessUnitId)
    @businessUnitId = businessUnitId
    url = URI("https://dtld-poc.appspot.com/_ah/api/dtldapi/v1/drivethrudashboard/reportinginit?businessUnitId=#{@businessUnitId}")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["cache-control"] = 'no-cache'

    response = http.request(request)
    if response.read_body != nil
      @init = JSON.parse(response.read_body)
    if @init["storeName"] != nil
      return @init["storeName"]
    else
      return @businessUnitId
    end
    else
      return @businessUnitId
    end
    
  end

  def dts
    
  end
  
  def dts_hourlies_live_do
    @@businessUnitId = current_person[:store]
    if (params[:storeId] != nil && params[:storeId] != "")
      if (params[:date] != nil && params[:date] != "")
        @storeid = params[:storeId]
        @date = Time.parse(params[:date])
        @response = reportdata(@storeid, @date, "Full", "Daily")
        if @response["success"] == true
          data = JSON.parse(@response["result"])
          dat = @response["averageValues"]
          averages = Hash[]
          dat.each do |key, value|
            averages[key] = value
          end
          @dtsday = DtsDaily.new(date: @date, COD1: averages["COD 1"].to_i, COD2: averages["COD 2"].to_i, HHOT: averages["HHOT"].to_i, Cashier: averages["Cashier"].to_i, Presenter: averages["Presenter"].to_i, OEPE: averages["OE-PE"].to_i, AST: averages["AST"].to_i, TAR_COD1: averages["TAR_COD 1"].to_i, TAR_COD2: averages["TAR_COD 2"].to_i, TAR_HHOT: averages["TAR_HHOT"].to_i, TAR_Cashier: averages["TAR_Cashier"].to_i, TAR_Presenter: averages["TAR_Presenter"].to_i, TAR_OEPE: averages["TAR_OE-PE"].to_i, TAR_AST: averages["TAR_AST"].to_i, datestring: @date.to_date, storeId: @storeid.to_s)
          if (DtsDaily.find_by(datestring: @date.to_date.to_s, storeId: @storeid.to_s) == nil)
            @dtsday.save
          end
          data = Hash[ data.collect {|k,v| [k.to_i, v] } ]
          @reportdata = data.sort
          stringstore = @storeid.to_s
          respon = JSON.parse('{"error" : false }')
          respon["store"] = stringstore
          respon["date"] = @date.to_date
          @info = respon
        else
          respon = JSON.parse('{"error" : true }')
          respon["store"] = stringstore
          respon["date"] = @date.to_date
          respon["message"] = @response["result"]

app/helpers/dts_hourlies_helper.rb
module DtsHourliesHelper
end

app/views/dts_hourlies/daypart.html.erb
<%- model_class = DtsHourly -%>
<div class="page-header">
  <h1>DTS Daypart</h1>
</div>
<%= flash_messages %>
<p>
Please enter 4 digit restaurant number. Ie: 0610 or 1074 <br/>
<%= form_tag({controller: "dts_hourlies", action: "daypart_do"}, method: "get", remote: true) do%>
<div class="form-group">
    <p>Store: <%= text_field_tag :storeId %>
    Date: <%= text_field_tag :date %>
    Daypart: <%= select_tag 'daypart', '<option value="1">Overnight</option><option value="2">Open</option><option value="3">Dayshift</option><option value="4">Evening</option>'.html_safe, prompt: "Select daypart" %>
    <%= submit_tag "Go", data: { disable_with: "Loading..." } %></p>
  </div>
  <script>
  $("#date").datepicker({
        format: "yyyy-mm-dd",
        weekStart: 1,
        maxViewMode: 2,
        endDate: "today",
        todayBtn: "linked",
        language: "en-GB",
        daysOfWeekHighlighted: "0,6",
        calendarWeeks: true,
        autoclose: true,
        todayHighlight: true
    });
  </script>
  <% end %>
</p>
<div id="daypart_table">
</div>

app/views/dts_hourlies/daypart_do.js.erb
$('#daypart_table').html("<%= j (render 'layouts/daypart') %>");
$('#daypart_table').slideDown(350);

app/views/dts_hourlies/dts.erb
<%= flash_messages %>
<h3>DTS - Dashboard</h3>
<p>
Please enter 4 digit restaurant number. Ie: 0610 or 1074 <br/>
<%= form_tag({controller: "dts_hourlies", action: "dts_post"}, method: "get") do %>
<div class="form-group">
    <%= text_field_tag :businessUnitId %>
    <%= submit_tag "Go" %>
  </div>
  <% end %>
</p>
<div class="col-sm-3">
<%= render "layouts/side" %>
</div>
<table>
<tr>
<%= render "layouts/side2" %>
</tr>
</table>

app/views/dts_hourlies/dts.html.erb
<%= flash_messages %>
<h3>DTS - Dashboard</h3>
<p>
Please enter 4 digit restaurant number. Ie: 0610 or 1074 <br/>
<%= form_tag({controller: "dts_hourlies", action: "dts_do"}, method: "get", remote: true) do %>
<div class="form-group">
    <%= text_field_tag :businessUnitId %>
    <%= submit_tag "Go", data: { disable_with: "Loading..." } %>
  </div>
  <% end %>
</p>
<div id="dash">
</div>

app/views/dts_hourlies/dts_do.js.erb
$('#dash').html("<%= j (render 'layouts/dashboard') %>");
$('#dash').slideDown(350);

app/views/dts_hourlies/dts_hourlies_live.erb
<%= flash_messages %>
<h3>DTS - Hourlies Live  </h3>

<p>
Please enter 4 digit restaurant number. Ie: 0610 or 1074 <br/>
<%= form_tag({controller: "dts_hourlies", action: "dts_hourlies_live_do"}, method: "get", remote: true) do%>
<div class="form-group">
    <p>Store: <%= text_field_tag :storeId %>
    Date: <%= text_field_tag :date %>
    <%= submit_tag "Go", data: { disable_with: "Loading..." } %></p>
  </div>
  <script>
  $("#date").datepicker({
        format: "yyyy-mm-dd",
        weekStart: 1,
        maxViewMode: 2,
        endDate: "today",
        todayBtn: "linked",
        language: "en-GB",
        daysOfWeekHighlighted: "0,6",
        calendarWeeks: true,
        autoclose: true,
        todayHighlight: true
    });
  </script>
  <% end %>
</p>
<div id="live">
</div>

app/views/dts_hourlies/dts_hourlies_live_do.js.erb
$('#live').html("<%= j (render 'layouts/live') %>");
$('#live').slideDown(350);

app/views/dts_hourlies/index.html.erb
<%- model_class = DtsHourly -%>
<%= flash_messages %>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<ul class="nav nav-tabs">
<% @stores.each_with_index do |store,index| %>
  <% if index == 0 %>
    <li class="active"><a data-toggle="tab" href="#<%=store.storeId%>"><%=store.storeId%></a></li>
  <% end %>
  <% if index != 0 %>
    <li><a data-toggle="tab" href="#<%=store.storeId%>"><%=store.storeId%></a></li>
  <% end %>
<% end %>
</ul>

<div class="tab-content">
  <% @stores.each_with_index do |store_hourly,index| %>
  <% if index == 0 %>
    <div id="<%=store_hourly.storeId%>" class="tab-pane fade in active">
    <h3>Store: <%=@storename[store_hourly.storeId]%></h3>
    
    <table id="table-<%=store_hourly.storeId%>" class="table table-hover table-responsive" style="font-size: x-small;">
  <thead>
    <tr>
      <th>Date</th>
      <th>Hour</th>
      <th><%= model_class.human_attribute_name(:cars) %></th>
      <th>COD1</th>
      <th>COD1 % </th>
      <th>COD2</th>
      <th>COD2 % </th>
      <th>HHOT</th>
      <th>HHOT % </th>
      <th><%= model_class.human_attribute_name(:Cashier) %></th>
      <th>Cashier % </th>
      <th><%= model_class.human_attribute_name(:Presenter) %></th>
      <th>Presenter % </th>
      <th>OEPE</th>
      <th>OEPE % </th>
      <th>AST</th>
      <th>AST % </th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @dts_hourlies.each do |dts_hourly| %>
      <% if dts_hourly.storeId == store_hourly.storeId %>
          <tr>
            <td style="text-align: center; vertical-align: middle;"><%= dts_hourly.datestring %></td>
            <td><%= link_to "#{dts_hourly.hour}:00", dts_hourly_path(dts_hourly) %></td>
            <td><%= dts_hourly.cars %></td>
            <td><%= dts_hourly.COD1 %></td>
            <td><%= dts_hourly.TAR_COD1 %>%</td>
            <td>
            <% if (dts_hourly.COD2 == nil)  %>
            -
            <% end %>
            <% if (dts_hourly.COD2 != nil)  %>
            <%= dts_hourly.COD2 %>
            <% end %>
            </td>
            <td>
            <% if (dts_hourly.COD2 == nil)  %>
            -
            <% end %>
            <% if (dts_hourly.COD2 != nil)  %>
            <%= dts_hourly.TAR_COD2 %> %
            <% end %>
            </td>
            <td>
            <% if (dts_hourly.HHOT == nil)  %>
            -
            <% end %>
            <% if (dts_hourly.HHOT != nil)  %>
            <%= dts_hourly.HHOT %>
            <% end %>
            </td>
            <td>
            <% if (dts_hourly.HHOT == nil)  %>
            -
            <% end %>
            <% if (dts_hourly.HHOT != nil)  %>
            <%= dts_hourly.TAR_HHOT %> %
            <% end %>
            </td>
            <td><%= dts_hourly.Cashier %></td>
            <td><%= dts_hourly.TAR_Cashier %>%</td>
            <td><%= dts_hourly.Presenter %></td>
            <td><%= dts_hourly.TAR_Presenter %>%</td>
            <td><%= dts_hourly.OEPE %></td>
            <td><%= dts_hourly.TAR_OEPE %>%</td>
            <td><%= dts_hourly.AST %></td>
            <td><%= dts_hourly.TAR_AST %>%</td>
            <td>
              <div class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
              <ul class="dropdown-menu">
                
                    <li><%= link_to t('.show', :default => t("helpers.links.show")),
                          dts_hourly_path(dts_hourly) %></li>
                    <li><%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_dts_hourly_path(dts_hourly) %></li>
                    <% if current_person.try(:admin?) %>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        dts_hourly_path(dts_hourly),
                        :method => 'delete',
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-danger' %>
                    </li>
                    <% end %>
                </ul>
              </div>
            </td>
          </tr>
      <% end %>
        
    <% end %>
  </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function () {
        $('#table-<%=store_hourly.storeId%>').each(function () {
            var Column_number_to_Merge = 1;
 
            // Previous_TD holds the first instance of same td. Initially first TD=null.
            var Previous_TD = null;
            var i = 1;
            $("tbody",this).find('tr').each(function () {
                // find the correct td of the correct column
                // we are considering the table column 1, You can apply on any table column
                var Current_td = $(this).find('td:nth-child(' + Column_number_to_Merge + ')');
                 
                if (Previous_TD == null) {
                    // for first row
                    Previous_TD = Current_td;
                    i = 1;
                } 
                else if (Current_td.text() == Previous_TD.text()) {
                    // the current td is identical to the previous row td
                    // remove the current td
                    Current_td.remove();
                    // increment the rowspan attribute of the first row td instance
                    Previous_TD.attr('rowspan', i + 1);
                    i = i + 1;
                } 
                else {
                    // means new value found in current td. So initialize counter variable i
                    Previous_TD = Current_td;
                    i = 1;
                }
            });
        });
    });
</script>
  </div>
  <% end %>
  <% if index != 0 %>
    <div id="<%=store_hourly.storeId%>" class="tab-pane fade">
    <h3>Store: <%=@storename[store_hourly.storeId]%></h3>
    
    <table id="table-<%=store_hourly.storeId%>" class="table table-hover table-responsive" style="font-size: x-small;">
  <thead>
    <tr>
      <th>Date</th>
      <th>Hour</th>
      <th><%= model_class.human_attribute_name(:cars) %></th>
      <th>COD1</th>
      <th>COD1 % </th>
      <th>COD2</th>
      <th>COD2 % </th>
      <th>HHOT</th>
      <th>HHOT % </th>
      <th><%= model_class.human_attribute_name(:Cashier) %></th>
      <th>Cashier % </th>
      <th><%= model_class.human_attribute_name(:Presenter) %></th>
      <th>Presenter % </th>
      <th>OEPE</th>
      <th>OEPE % </th>
      <th>AST</th>
      <th>AST % </th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @dts_hourlies.each do |dts_hourly| %>
      <% if dts_hourly.storeId == store_hourly.storeId %>
          <tr>
            <td style="text-align: center; vertical-align: middle;"><%= dts_hourly.datestring %></td>
            <td><%= link_to "#{dts_hourly.hour}:00", dts_hourly_path(dts_hourly) %></td>
            <td><%= dts_hourly.cars %></td>
            <td><%= dts_hourly.COD1 %></td>
            <td><%= dts_hourly.TAR_COD1 %>%</td>
            <td>
            <% if (dts_hourly.COD2 == nil)  %>
            -
            <% end %>
            <% if (dts_hourly.COD2 != nil)  %>
            <%= dts_hourly.COD2 %>
            <% end %>
            </td>
            <td>
            <% if (dts_hourly.COD2 == nil)  %>
            -
            <% end %>
            <% if (dts_hourly.COD2 != nil)  %>
            <%= dts_hourly.TAR_COD2 %> %
            <% end %>
            </td>
            <td>
            <% if (dts_hourly.HHOT == nil)  %>
            -
            <% end %>
            <% if (dts_hourly.HHOT != nil)  %>
            <%= dts_hourly.HHOT %>
            <% end %>
            </td>
            <td>
            <% if (dts_hourly.HHOT == nil)  %>
            -
            <% end %>
            <% if (dts_hourly.HHOT != nil)  %>
            <%= dts_hourly.TAR_HHOT %> %
            <% end %>
            </td>
            <td><%= dts_hourly.Cashier %></td>
            <td><%= dts_hourly.TAR_Cashier %>%</td>
            <td><%= dts_hourly.Presenter %></td>
            <td><%= dts_hourly.TAR_Presenter %>%</td>
            <td><%= dts_hourly.OEPE %></td>
            <td><%= dts_hourly.TAR_OEPE %>%</td>
            <td><%= dts_hourly.AST %></td>
            <td><%= dts_hourly.TAR_AST %>%</td>
            <td>
              <div class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
              <ul class="dropdown-menu">
                
                    <li><%= link_to t('.show', :default => t("helpers.links.show")),
                          dts_hourly_path(dts_hourly) %></li>
                    <li><%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_dts_hourly_path(dts_hourly) %></li>
                    <% if current_person.try(:admin?) %>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              dts_hourly_path(dts_hourly),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
                    </li>
                    <% end %>
                </ul>
              </div>
            </td>
          </tr>
      <% end %>
        
    <% end %>
  </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function () {
        $('#table-<%=store_hourly.storeId%>').each(function () {
            var Column_number_to_Merge = 1;
 
            // Previous_TD holds the first instance of same td. Initially first TD=null.
            var Previous_TD = null;
            var i = 1;
            $("tbody",this).find('tr').each(function () {
                // find the correct td of the correct column
                // we are considering the table column 1, You can apply on any table column
                var Current_td = $(this).find('td:nth-child(' + Column_number_to_Merge + ')');
                 
                if (Previous_TD == null) {
                    // for first row
                    Previous_TD = Current_td;
                    i = 1;
                } 
                else if (Current_td.text() == Previous_TD.text()) {
                    // the current td is identical to the previous row td
                    // remove the current td
                    Current_td.remove();
                    // increment the rowspan attribute of the first row td instance
                    Previous_TD.attr('rowspan', i + 1);
                    i = i + 1;
                } 
                else {
                    // means new value found in current td. So initialize counter variable i
                    Previous_TD = Current_td;
                    i = 1;
                }
            });
        });
    });
</script>
  </div>
  <% end %>
<% end %>
</div>



<%= link_to t('.new', :default => t("helpers.links.new")),
            new_dts_hourly_path,
            :class => 'btn btn-default' %>