config/routes.rb
Rails.application.routes.draw do
  resources :dts_hourlies
  devise_for :people
  resources :people
  resources :names
  resources :activity
  get "/dts", to: "dts_hourlies#dts", as: "dts"
  get "/dts/hourly/live", to: "dts_hourlies#dts_hourlies_live", as: "dts_hourlies_live"
  get "/dts/daypart", to: "dts_hourlies#daypart", as: "daypart"
  get "/dts/daypart/do", to: "dts_hourlies#daypart_do"
  get "/dts/hourly/live/do", to: "dts_hourlies#dts_hourlies_live_do"
  get "/dts/do", to: "dts_hourlies#dts_do", as: "dts_do"
  get "/app/views/home/index", to: "home#index", as: "index"
  get "/setup", to: "home#setup", as: "setup"
  get "/store", to: "home#store", as: "store"
  get "/setup/dp/do", to: "home#setup_dp_do", as: "setup_dp_do"
  get "/dts/fetch", to: "dts_hourlies#dts_fetch", as: "dts_fetch"
  root 'home#index'
end

app/views/layouts/_dashboard.html.erb
<div class="col-sm-3">
<%= render "layouts/side" %>
</div>
<table>
<tr>
<%= render "layouts/side2" %>
</tr>
</table>

app/views/layouts/_daypart.html.erb
<h4><strong>Store: </strong><%= @storename[@storeId]%> <strong>Date: </strong><%=@date%> <strong>Daypart: </strong><%=@daypart_str[@daypart_num.to_i]%></h4>
  <% if @return[0] != nil %>
    <table id="table" class="table table-hover table-responsive" style="font-size: small; width: 25%">
      <thead>
        <tr>
          <td><strong>Hour </strong></td>
          <td><strong>AST </strong></td>
          <td><strong>OEPE </strong></td>
          <td><strong>Cars </strong></td>
        </tr>
      </thead>
      <tbody>
        <% @return.each do |item| %>
          <tr>
            <td><%= item.hour %>:00 - <%= item.hour+1 %>:00</td>
            <td><%= item.AST %></td>
            <td><%= item.OEPE %></td>
            <td><%= item.cars %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td><strong>Sum: </strong></td>
          <td><strong><%=@avg_ast%></strong></td>
          <td><strong><%=@avg_oepe%></strong></td>
          <td><strong><%=@cars%></strong></td>
        </tr>
      </tfoot>
    </table>
  <% else %>
    <div class="well well-sm" style="margin: auto !important; border-left: 6px solid orange !important;"><h5> <p><strong>Error</strong></p>No information available for the given period.</h5><br/><p><samp><%= @storeId%>.<%=@date%>.<%=@daypart_str[@daypart_num.to_i]%></samp></p></div>
  <% end %>

app/views/layouts/_dp_def_table.html.erb
<% @dp_def[store_hourly].each_with_index do |dp,index| %>
    <tr>
        <% if dp.start != nil %>
        <td><%= label_tag 'daypart_num[]', @daypart_str[dp.daypart_num] %></td>
            <%=hidden_field_tag 'daypart_num[]', dp.daypart_num %>
            <td><%= text_field_tag 'start[]', dp.start, size: 5 %>:00</td>
            <td><%= text_field_tag 'finish[]', dp.finish, size: 5 %>:00</td>
            <td><%= check_box 'open', index+1, {:checked => dp.open}, 'true', 'false' %></td>
            <%= hidden_field_tag :store, store_hourly %>
        <% else %>
            <td><%= label_tag 'daypart_num[]', @daypart_str[dp.daypart_num] %></td>
            <%=hidden_field_tag 'daypart_num[]', dp.daypart_num %>
            <td><%= text_field_tag 'start[]', dp.start, size: 5 %>:00</td>
            <td><%= text_field_tag 'finish[]', dp.finish, size: 5 %>:00</td>
            <td><%= check_box 'open', index+1, {:checked => dp.open}, 'true', 'false' %></td>
            <%=hidden_field_tag :store, store_hourly %>
        <% end %>
    </tr>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Tracker</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if person_signed_in? %>
        <li class="active"><a href="/store">UK-<%= current_person.store %> <span class="sr-only">(current)</span></a></li>
      <% if current_person.try(:admin?) %>
        <li><%= link_to "Setup", setup_url %></li>
      <% end %> 
        <li><%= link_to "People", people_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">DTS<span class="caret"></span></a>
          <ul class="dropdown-menu">
            
                <li><%= link_to "DTS Dashboard", dts_path%></a></li>
                <li><%= link_to "DTS Daypart", daypart_url %></li>
                <li><%= link_to "DTS Hour Live", dts_hourlies_live_path %></li>
                <li><%= link_to "DTS Hourlies", dts_hourlies_path %></li>
          </ul>
        </li>
      <% end %>  
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if person_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "#{current_person.firstname} #{current_person.lastname}" %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            
                <li><%= link_to "Profile", person_path(current_person)%></a></li>
                <li><a href="/store">Store: <%= current_person.store %></a></li>
                <li><a href="#">Settings</a></li>
                <li role="separator" class="divider"></li>
                <li>
                <%= link_to('Logout', destroy_person_session_path, method: :delete) %>        
                </li>
                <% else %>
                <li>
                <%= link_to('Login', new_person_session_path)  %>  
                </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_live.html.erb
<% if @info["error"] == false %>
  <div class="well well-sm" style="width: 90%;"><h4><strong> Store: </strong><%= @info["store"] %> <strong>Date: </strong> <%= @info["date"]%></h4>
    <table class="table table-hover table-responsive" style="font-size: x-small">
    <% if @reportdata[0][1]["COD 2"] == nil %>
    <thead><th>Hour</th><th>COD 1</th><th>COD 1 %</th><th>HHOT</th><th>HHOT %</th><th>Cashier</th><th>Cashier %</th><th> Presenter</th>
    <th>Presenter %</th><th>AST</th><th>AST %</th><th>OEPE</th><th>OEPE %</th><th>Cars</th></thead><tbody>
    <% @reportdata.each_with_index do |hour,index| %>
    <tr>
    <td><%=hour[0]%>:00 - <%=hour[0].to_i+1%>:00 </td>
    <td><%=hour[1]["COD 1"]%></td>
    <td><%=hour[1]["TAR_COD 1"]%>%</td>
    <td><%=hour[1]["HHOT"]%></td>
    <td><%=hour[1]["TAR_HHOT"]%>%</td>
    <td><%=hour[1]["Cashier"]%></td>
    <td><%=hour[1]["TAR_Cashier"]%>%</td>
    <td><%=hour[1]["Presenter"]%></td>
    <td><%=hour[1]["TAR_Presenter"]%>%</td>
    <td><strong><%=hour[1]["AST"]%></strong></td>
    <td><%=hour[1]["TAR_AST"]%>%</td>
    <td><strong><%=hour[1]["OE-PE"]%></strong></td>
    <td><%=hour[1]["TAR_OE-PE"]%>%</td>
    <td><%=hour[1]["Cars"]%></td>
    </tr>
    <% end %>
    <% end %>
    <% if @reportdata[0][1]["HHOT"] == nil %>
    <thead><th>Hour</th><th>COD 1</th><th>COD 1 %</th><th>COD 2</th><th>COD 2 %</th><th>Cashier</th><th>Cashier %</th><th> Presenter</th>
    <th>Presenter %</th><th>AST</th><th>AST %</th><th>OEPE</th><th>OEPE %</th><th>Cars</th></thead><tbody>
    <% @reportdata.each_with_index do |hour,index| %>
    <tr>
    <td><%=hour[0]%>:00 - <%=hour[0].to_i+1%>:00 </td>
    <td><%=hour[1]["COD 1"]%></td>
    <td><%=hour[1]["TAR_COD 1"]%>%</td>
    <td><%=hour[1]["COD 2"]%></td>
    <td><%=hour[1]["TAR_COD 2"]%>%</td>
    <td><%=hour[1]["Cashier"]%></td>
    <td><%=hour[1]["TAR_Cashier"]%>%</td>
    <td><%=hour[1]["Presenter"]%></td>
    <td><%=hour[1]["TAR_Presenter"]%>%</td>
    <td><strong><%=hour[1]["AST"]%></strong></td>
    <td><%=hour[1]["TAR_AST"]%>%</td>
    <td><strong><%=hour[1]["OE-PE"]%></strong></td>
    <td><%=hour[1]["TAR_OE-PE"]%>%</td>
    <td><%=hour[1]["Cars"]%></td>
    </tr>
    <% end %>
    <% end %>
    </tbody>
    </table></div>
<% end %>

<% if @info["error"] == true %>
  <div class="well well-sm" style="margin: auto !important; border-left: 6px solid orange !important;"><h5> <p><strong>Error</strong></p><%= @info["message"] %> </h5><h9><i>Store:<%=@info["store"]%>Date:<%=@info["date"]%></i></h9></div>
        
<% end %>    

app/views/layouts/_schedule.html.erb
<p><h4>Schedule</h4>(<%=@begin%> - <%=@end%>)</p>
</br>
<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span></span>This page will NOT save any data entered yet.
</div>
<table class="table table-bordered table-responsive" style="width: 1000px;">
    <thead>
        <tr>
            <th style="vertical-align: middle; text-align: center;">Week #</th>
            <th style="vertical-align: middle; ">Monday</th>
            <th style="vertical-align: middle; ">Tuesday</th>
            <th style="vertical-align: middle; ">Wednesday</th>
            <th style="vertical-align: middle; ">Thursday</th>
            <th style="vertical-align: middle; ">Friday</th>
            <th style="vertical-align: middle; ">Saturday</th>
            <th style="vertical-align: middle; ">Sunday</th>
        </tr>
    </thead>
    <tbody>
        <tr style="height: 150px;">
        <td style="vertical-align: middle; text-align: center;">Week <%=@wn%></td>
            <% @week.each do |day| %>
              <td style="padding: 0px;"><table style="margin: 0px;" class="table table-responsive">
                <tr>
                    <td><%=day%></td>
                </tr>
                <tr>
                    <td>Overnight</br><%= select_tag "names", options_for_select(@names.collect {|p| [ "#{p['firstname']} #{p['lastname'][0]}", p['nameid'] ] }, 0)%></td>
                </tr>
                <tr>
                    <td>Open</br><%= select_tag "names", options_for_select(@names.collect {|p| [ "#{p['firstname']} #{p['lastname'][0]}", p['nameid'] ] }, 0)%></td>
                </tr>
                <tr>
                    <td>Dayshift</br><%= select_tag "names", options_for_select(@names.collect {|p| [ "#{p['firstname']} #{p['lastname'][0]}", p['nameid'] ] }, 0)%></td>
                </tr>
                <tr>
                    <td>Evening</br><%= select_tag "names", options_for_select(@names.collect {|p| [ "#{p['firstname']} #{p['lastname'][0]}", p['nameid'] ] }, 0)%></td>
                </tr>
                </table></td>
            <% end %>
        </tr>
    </tbody>
</table>

app/views/layouts/_side.html.erb
<% if (@dailyranking != nil) %>
<div class="well well-sm">
        <h4>Daily Ranking</h4>
            <br/>
            <h5>Top 3</h5>
            <% @dailyranking["items"].each_with_index do |item, index| %>
                <p>
                <% if index.equal?(3) %>
                <hr/>
                <h5>Group</h5>
                <% end %>
                <%= item["rankingPosition"] %>: <strong><%=item["storeName"]%></strong><br/>
                Rolling hour AST: <strong><%= item["averageASTForLastHour"].chomp("000") %></strong><br/>
                Current hour AST: <strong><%= item["hourAverageAST"].chomp("000") %> </strong>Ratio: <strong><%=item["hourTargetAchievedRatioAST"]%>%</strong><br/>
                </p>
            <% end %>
            <% else %>
            <% end %>
        </div>

app/views/layouts/_side2.html.erb
<% if @hourlysummary.nil? != true %>
<% if @hourlysummary[0].nil? != true %>
    
        <% if @hourlysummary[0]['error'] != true%>
            <% @hourlysummary.each_with_index do |store,index| %>
                <td>
                <div class="well well-sm" style="height = 100%;">
                    
                    <h4><%= store["store"] %></h4>
                    <h6><strong>Current hour</strong></h6>
                    <br/>
                    <p>OEPE:<strong> <%= store["averageOEPETiming"].chomp("000")%></strong></p>
                    <p>Cars:<strong> <%= store["carCount"]%></p></strong>
                        <% store["sensorsSummary"].each do |sensor| %>
                            <p><%= sensor["sensorName"] %>: <strong><%= sensor["averageTime"].chomp('000') %> </strong>Ratio: <strong><%= sensor["targetAchievedRatio"] %>%</strong></p>
                        <% end %>
                    
                    </div>
                </div>
                </td>
                <% if ((index+1)%3 == 0) %>
                </tr><tr>
                <% end %>
            <% end %>
        <% else %>
            <td><div class="well well-sm" style="margin: auto !important; border-left: 6px solid orange !important;"><h5> <p><strong>Error</strong></p><%= @hourlysummary[0]["message"] %> </h5></div></td>
        <% end %>
<% end %>
<% else %>
            <td><div class="well well-sm" style="margin: auto !important; border-left: 6px solid orange !important;"><h5> <p><strong>Error</strong></p><%= @hourlysummary["message"] %> </h5></div></td>
        <% end %>

app/views/layouts/_weekly.html.erb
<p><h4>Weekly results</h4>(<%=@begin%> - <%=@end%>)</p>
<strong>Average AST: </strong> <%=@ast%>
<strong>Average OEPE: </strong><%=@oepe%>
<strong>Total cars: </strong><%=@cars%> </br></br>
<table id="table" class="table table-responsive table-condensed table-hover" style="width: 500px;">
    <thead>
        <tr>
            <th>Date</th>
            <th>Daypart</th>
            <th>Manager</th>
            <th>OEPE</th>
            <th>AST</th>
            <th>Cars</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <% @result.each_with_index do |hour,index| %>
        <tr>
            <td><%= hour[0] %></td>
            <% if hour[1] == 4 %>
                <td colspan="5"><%= @dayparts[hour[1]] %></td>
                <td><%= link_to "Fetch now!", "/dts/fetch?date=#{hour[0]}", class: "btn btn-success btn-xs", remote: true, data: {disable_with: "Loading..." } %></td>
            <% else %>
                <td><%= @dayparts[hour[1]] %></td>
                <td><%= hour[2] %></td>
                <td><%= hour[3] %></td>
                <td><%= hour[4] %></td>
                <td><%= hour[5] %></td>
                
                <% if (hour[1] == 1)%>
                  <td><%= link_to "Fetch again?", "/dts/fetch?date=#{hour[0]}", class: "btn btn-warning btn-xs", remote: true, data: {disable_with: "Loading..." } %></td>
                <% end %>
                
                <% end %>            
        </tr>
    <% end %>
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function () {
        $('#table').each(function () {
            var Column_number_to_Merge = 1;
 
            // Previous_TD holds the first instance of same td. Initially first TD=null.
            var Previous_TD = null;
            var i = 1;
            $("tbody",this).find('tr').each(function () {
                // find the correct td of the correct column
                // we are considering the table column 1, You can apply on any table column
                var Current_td = $(this).find('td:nth-child(' + Column_number_to_Merge + ')');
                 
                if (Previous_TD == null) {
                    // for first row
                    Previous_TD = Current_td;
                    i = 1;
                } 
                else if (Current_td.text() == Previous_TD.text()) {
                    // the current td is identical to the previous row td
                    // remove the current td
                    Current_td.remove();
                    // increment the rowspan attribute of the first row td instance
                    Previous_TD.attr('rowspan', i + 1);
                    i = i + 1;
                } 
                else {
                    // means new value found in current td. So initialize counter variable i
                    Previous_TD = Current_td;
                    i = 1;
                }
            });
        });
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>